version: '2'

services:
  proxy:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  server:
    image: boilerplate-server
    build: ./server
  client:
    image: boilerplate-client
    build: ./client
