version: '2'

services:
  proxy:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  server:
    image: boilerplate-server
    build: ./server
    environment:
      - MONGO_URI=mongodb://db:27017/app
    volumes:
      - ./server:/server:ro
  client:
    image: boilerplate-client
    build: ./client
    volumes:
      - ./client/build:/client/build
  db:
    image: mongo:4
    volumes:
      - app-db:/data/db
volumes:
  app-db: